CREATE USER IF NOT EXISTS "SA" SALT '1b05e2bcf8b5c14f' HASH 'ee3149d52fbf225205ba0e3602c533a0990600186d4b4d2c0e3d0578e141a3ed' ADMIN;
CREATE MEMORY TABLE "PUBLIC"."USERS"(

    "IS_ACTIVE" BOOLEAN NOT NULL,

    "CREATION_USER_AT" TIMESTAMP(6),

    "LAST_LOGIN_AT" TIMESTAMP(6),

    "MODIFIED_USER_AT" TIMESTAMP(6),

    "ID" UUID NOT NULL,

    "EMAIL" CHARACTER VARYING(255),

    "NAME" CHARACTER VARYING(255),

    "PASSWORD" CHARACTER VARYING(255)

);
CREATE MEMORY TABLE "PUBLIC"."PHONE"(

    "ID" UUID NOT NULL,

    "USER_ID" UUID,

    "CITY_CODE" CHARACTER VARYING(255),

    "COUNTRY_CODE" CHARACTER VARYING(255),

    "NUMBER" CHARACTER VARYING(255)

);
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("ID");
ALTER TABLE "PUBLIC"."PHONE" ADD CONSTRAINT "PUBLIC"."FKIK7A2ETDORYBVOOLVCHFCVGKX" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."PHONE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");